In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return 1*(1-x)

In [4]:
training_inputs=np.array([[0,1,1],[1,0,0],[1,0,1],[0,1,0]])
print(training_inputs)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]]


In [5]:
training_outputs=np.array([[0,1,1,0]]).T
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [6]:
weights=np.array([[0],[0],[0]],dtype='float64')
print(weights)

[[0.]
 [0.]
 [0.]]


In [7]:
#training part
for i in range(200):
    input_layer=training_inputs
    outputs=sigmoid(np.dot(input_layer,weights))
    error=training_outputs-outputs
    adjustments=error*sigmoid_derivative(outputs)
    weights+=np.dot(input_layer.T,adjustments)

In [8]:
print(outputs)

[[0.00200483]
 [0.97085279]
 [0.9563557 ]
 [0.00304431]]
