In [1]:
import numpy as np

In [2]:
class NeuralNetwork:
    def __init__(self):
        self.weights=np.array([[0],[0],[0]],dtype='float64')
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    def sigmoid_derivative(self,x):
        return 1*(1-x)
    def think(self,inputs):
        inputs=inputs.astype(float)
        outputs=self.sigmoid(np.dot(inputs,self.weights))
        return outputs
    def train(self,training_inputs, training_outputs,iterations):
        for i in range(iterations):
            outputs=self.think(training_inputs)
            error=training_outputs-outputs
            adjustments=error*self.sigmoid_derivative(outputs)
            self.weights+=np.dot(training_inputs.T,adjustments)

In [3]:
training_inputs=np.array([[0,1,1],[1,0,0],[1,0,1],[0,1,0]])
print(training_inputs)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]]


In [4]:
training_outputs=np.array([[0,1,1,0]]).T
print(training_outputs)

[[0]
 [1]
 [1]
 [0]]


In [5]:
nn=NeuralNetwork()
nn.train(training_inputs,training_outputs,10000)

In [6]:
A=int(input("Input 1 : "))
B=int(input("Input 2 : "))
C=int(input("Input 3 : "))
print("Output : ",nn.think(np.array([A,B,C]))[0].round())

Input 1 :  1
Input 2 :  1
Input 3 :  0


Output :  0.0
