In [1]:
import numpy as np
import pandas as pd

In [2]:
#Create a NumPy array with elements [10,20,30,40,50]
ar=np.array([10,20,30,40,50])
print(ar)

[10 20 30 40 50]


In [3]:
#Create a NumPy array off all zeros of size 5.
ar1=np.zeros(50)
print(ar1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [4]:
#Create a NumPy array off all ones of shape (3,3)
ar2=np.ones((3,3))
print(ar2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#find the data type of a NumPy array.
ar3=np.array(['rakhi','ratnesh','amit','ankit'])
print(ar3.dtype)

<U7


In [6]:
#5 create  a array
ar4=np.linspace(0,1,5)
print(ar4)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
#6
ar5=np.array([1,2,3,4,5,6])
print(ar5)
ar6=ar5.reshape(3,2)
print(ar6)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [8]:
#7
print("Dimension=",ar6.ndim)
print("shape=",ar6.shape)

Dimension= 2
shape= (3, 2)


In [9]:
#8

In [10]:
#9
ser1=pd.Series([1,2,3,4,5,6,7,8])
print(ser1)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64


In [11]:
#10
data={
    "EmpID":[1,2,3,4,5],
    "EmpName":['Abc','cde',"efg","ghi","ryd"],
    "Salary":[1000,2330,3400,5000,3000]
}
df=pd.DataFrame(data)
df

,EmpID,EmpName,Salary
0,1,Abc,1000
1,2,cde,2330
2,3,efg,3400
3,4,ghi,5000
4,5,ryd,3000


In [12]:
#11

In [13]:
#13
rows,columns=df.shape
print('Rows=',rows)
print('Columns=',columns)

Rows= 5
Columns= 3


In [14]:
#14
print(df.columns)

Index(['EmpID', 'EmpName', 'Salary'], dtype='object')


In [16]:
#15
df("EmpID")

TypeError: 'DataFrame' object is not callable